ESPIDF = /Users/pg/Development/repositories/esp-idf
PORT = /dev/tty.usbserial-DN02N256
#FLASH_MODE = qio
#FLASH_SIZE = 4MB
CROSS_COMPILE = /Users/pg/Development/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-

include /Users/pg/Development/repositories/micropython-esp32/esp32/Makefile